[workspace]
resolver = "2"
members = ["crates/pgforge-core", "crates/pgforge-cli", "src-tauri"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
authors = ["pgforge contributors"]
repository = "https://github.com/pgforge/pgforge"

[workspace.dependencies]
pgforge-core = { path = "crates/pgforge-core" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
