//! El texto de cada objeto, escrito a partir de lo leído.
//!
//! Sirve para dos cosas a la vez, y por eso vive suelto: es lo que la interfaz muestra lado a lado
//! y es lo que [`super::sync`] emite cuando un objeto falta entero del otro lado. Que sean el mismo
//! generador es lo que garantiza que el SQL propuesto sea exactamente lo que se mostró, y no una
//! reconstrucción parecida.
//!
//! Todo acá es función pura sobre [`super::snapshot`]: no hay servidor al que preguntarle nada.

use crate::ddl::quote_ident;
use crate::ddl::table::Identity;

use super::snapshot::{Column, NamedDef, Sequence, Table, TypeDef, TypeKind, View};

/// `esquema.nombre`, con cada mitad citada solo si hace falta.
pub fn qualified(schema: &str, name: &str) -> String {
    format!("{}.{}", quote_ident(schema), quote_ident(name))
}

/// Un literal de texto: comillas simples y las de adentro dobladas. `quote_ident` no sirve para las
/// etiquetas de una enumeración, que no son identificadores.
fn literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// Una columna tal como se escribe dentro de un `CREATE TABLE`.
pub fn column_clause(column: &Column) -> String {
    let mut sql = format!("{} {}", quote_ident(&column.name), column.type_name);

    if let Some(collation) = &column.collation {
        sql.push_str(&format!(" COLLATE {}", quote_ident(collation)));
    }
    if let Some(expression) = &column.generated {
        sql.push_str(&format!(" GENERATED ALWAYS AS ({expression}) STORED"));
    }
    if let Some(identity) = column.identity {
        sql.push_str(match identity {
            Identity::Always => " GENERATED ALWAYS AS IDENTITY",
            Identity::ByDefault => " GENERATED BY DEFAULT AS IDENTITY",
        });
    }
    if column.not_null {
        sql.push_str(" NOT NULL");
    }
    if let Some(default) = &column.default {
        sql.push_str(&format!(" DEFAULT {default}"));
    }

    sql
}

/// El `CREATE TABLE` de una tabla, sin sus restricciones ni sus índices.
///
/// Van aparte a propósito: una clave foránea puede apuntar a una tabla que todavía no se creó, así
/// que el orden que sirve es todas las tablas primero y las restricciones después.
pub fn create_table(schema: &str, table: &Table) -> String {
    let columns = table
        .columns
        .iter()
        .map(|column| format!("    {}", column_clause(column)))
        .collect::<Vec<_>>()
        .join(",\n");

    let mut sql = format!(
        "CREATE TABLE {} (\n{columns}\n)",
        qualified(schema, &table.name)
    );
    if let Some(partition_by) = &table.partition_by {
        sql.push_str(&format!("\n{partition_by}"));
    }
    sql.push(';');
    sql
}

/// `ALTER TABLE … ADD CONSTRAINT …`, con la definición que devolvió el servidor.
pub fn add_constraint(schema: &str, table: &str, constraint: &NamedDef) -> String {
    format!(
        "ALTER TABLE {} ADD CONSTRAINT {} {};",
        qualified(schema, table),
        quote_ident(&constraint.name),
        constraint.definition
    )
}

pub fn create_view(schema: &str, view: &View, replace: bool) -> String {
    let keyword = match (view.materialized, replace) {
        (true, _) => "CREATE MATERIALIZED VIEW",
        (false, true) => "CREATE OR REPLACE VIEW",
        (false, false) => "CREATE VIEW",
    };
    format!(
        "{keyword} {} AS\n{};",
        qualified(schema, &view.name),
        view.definition.trim_end().trim_end_matches(';')
    )
}

pub fn create_sequence(schema: &str, sequence: &Sequence) -> String {
    let mut sql = format!(
        "CREATE SEQUENCE {}\n    AS {}\n    START WITH {}\n    INCREMENT BY {}\n    \
         MINVALUE {}\n    MAXVALUE {}\n    CACHE {}",
        qualified(schema, &sequence.name),
        sequence.type_name,
        sequence.start,
        sequence.increment,
        sequence.min_value,
        sequence.max_value,
        sequence.cache
    );
    if sequence.cycle {
        sql.push_str("\n    CYCLE");
    }
    sql.push(';');
    sql
}

pub fn create_type(schema: &str, definition: &TypeDef) -> String {
    let name = qualified(schema, &definition.name);

    match definition.kind {
        TypeKind::Enum => {
            let labels = definition
                .labels
                .iter()
                .map(|label| format!("    {}", literal(label)))
                .collect::<Vec<_>>()
                .join(",\n");
            format!("CREATE TYPE {name} AS ENUM (\n{labels}\n);")
        }
        TypeKind::Composite => {
            let fields = definition
                .fields
                .iter()
                .map(|field| format!("    {} {}", quote_ident(&field.name), field.type_name))
                .collect::<Vec<_>>()
                .join(",\n");
            format!("CREATE TYPE {name} AS (\n{fields}\n);")
        }
        TypeKind::Domain => {
            let mut sql = format!(
                "CREATE DOMAIN {name} AS {}",
                definition.base.as_deref().unwrap_or("text")
            );
            if let Some(default) = &definition.default {
                sql.push_str(&format!("\n    DEFAULT {default}"));
            }
            if definition.not_null {
                sql.push_str("\n    NOT NULL");
            }
            for check in &definition.checks {
                sql.push_str(&format!(
                    "\n    CONSTRAINT {} {}",
                    quote_ident(&check.name),
                    check.definition
                ));
            }
            sql.push(';');
            sql
        }
        TypeKind::Range => format!(
            "CREATE TYPE {name} AS RANGE (\n    subtype = {}\n);",
            definition.base.as_deref().unwrap_or("text")
        ),
    }
}

/// La tabla entera: el `CREATE TABLE` más lo que cuelga de él. Es lo que se muestra de un lado
/// cuando la tabla no existe del otro.
pub fn describe_table(schema: &str, table: &Table) -> String {
    let mut parts = vec![create_table(schema, table)];
    for constraint in &table.constraints {
        parts.push(add_constraint(schema, &table.name, constraint));
    }
    for index in &table.indexes {
        parts.push(format!("{};", index.definition));
    }
    parts.join("\n")
}

pub fn describe_view(schema: &str, view: &View) -> String {
    let mut parts = vec![create_view(schema, view, false)];
    for index in &view.indexes {
        parts.push(format!("{};", index.definition));
    }
    parts.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::snapshot::{Field, RelationKind};

    fn column(name: &str, type_name: &str) -> Column {
        Column {
            name: name.to_owned(),
            type_name: type_name.to_owned(),
            not_null: false,
            default: None,
            identity: None,
            generated: None,
            collation: None,
        }
    }

    #[test]
    fn escribe_una_tabla_con_sus_restricciones() {
        let table = Table {
            name: "clientes".to_owned(),
            kind: RelationKind::Ordinary,
            partition_by: None,
            columns: vec![
                Column {
                    not_null: true,
                    identity: Some(Identity::Always),
                    ..column("id", "bigint")
                },
                column("nombre", "text"),
            ],
            constraints: vec![NamedDef {
                name: "clientes_pkey".to_owned(),
                definition: "PRIMARY KEY (id)".to_owned(),
            }],
            indexes: vec![NamedDef {
                name: "clientes_nombre_idx".to_owned(),
                definition: "CREATE INDEX clientes_nombre_idx ON app.clientes USING btree (nombre)"
                    .to_owned(),
            }],
        };

        let sql = describe_table("app", &table);
        assert!(sql.contains("CREATE TABLE app.clientes ("));
        assert!(sql.contains("id bigint GENERATED ALWAYS AS IDENTITY NOT NULL"));
        assert!(
            sql.contains("ALTER TABLE app.clientes ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);")
        );
        assert!(
            sql.contains("CREATE INDEX clientes_nombre_idx ON app.clientes USING btree (nombre);")
        );
    }

    #[test]
    fn una_enumeracion_escapa_sus_valores() {
        let definition = TypeDef {
            name: "estado".to_owned(),
            kind: TypeKind::Enum,
            labels: vec!["activo".to_owned(), "de'baja".to_owned()],
            fields: Vec::new(),
            base: None,
            not_null: false,
            default: None,
            checks: Vec::new(),
        };

        assert_eq!(
            create_type("app", &definition),
            "CREATE TYPE app.estado AS ENUM (\n    'activo',\n    'de''baja'\n);"
        );
    }

    #[test]
    fn un_compuesto_lista_sus_campos() {
        let definition = TypeDef {
            name: "direccion".to_owned(),
            kind: TypeKind::Composite,
            labels: Vec::new(),
            fields: vec![
                Field {
                    name: "calle".to_owned(),
                    type_name: "text".to_owned(),
                },
                Field {
                    name: "numero".to_owned(),
                    type_name: "integer".to_owned(),
                },
            ],
            base: None,
            not_null: false,
            default: None,
            checks: Vec::new(),
        };

        assert_eq!(
            create_type("app", &definition),
            "CREATE TYPE app.direccion AS (\n    calle text,\n    numero integer\n);"
        );
    }

    #[test]
    fn una_vista_materializada_no_admite_replace() {
        let view = View {
            name: "ventas".to_owned(),
            materialized: true,
            definition: " SELECT 1;".to_owned(),
            indexes: Vec::new(),
        };
        assert!(create_view("app", &view, true).starts_with("CREATE MATERIALIZED VIEW app.ventas"));
    }
}
