//! Los comandos de vista previa, ejercitados con la carga que manda la interfaz.
//!
//! Estos comandos no tocan la red: reciben lo que `ipc.ts` serializa y delegan en las funciones
//! puras del núcleo. Por eso se pueden probar sin servidor y sin ventana, y por eso conviene —es la
//! promesa de la vista previa: lo que se muestra es exactamente lo que se va a ejecutar. Si la
//! traducción de argumentos pierde un campo, el usuario aprueba un SQL y se ejecuta otro.
//!
//! Los payloads se arman como **JSON**, no construyendo los tipos de Rust: así lo que se verifica
//! también es el contrato de serde con la interfaz —`camelCase` en todo, enums etiquetados con
//! `kind` (o con `on` en los privilegios)—. Un `rename_all` que se caiga rompe acá.

use pgforge_app_lib::commands;
use pgforge_core::data::{Change, ExportSpec, ImportSpec, TableShape};
use pgforge_core::ddl::comment::CommentChange;
use pgforge_core::ddl::database::DatabaseChange;
use pgforge_core::ddl::domain::DomainChange;
use pgforge_core::ddl::extension::ExtensionChange;
use pgforge_core::ddl::index::IndexDef;
use pgforge_core::ddl::policy::PolicyChange;
use pgforge_core::ddl::privilege::PrivilegeChange;
use pgforge_core::ddl::role::RoleChange;
use pgforge_core::ddl::schema::SchemaChange;
use pgforge_core::ddl::sequence::SequenceChange;
use pgforge_core::ddl::table::TableChange;
use pgforge_core::ddl::trigger::TriggerChange;
use pgforge_core::ddl::types::TypeChange;
use pgforge_core::ddl::view::ViewChange;
use pgforge_core::settings::SettingChange;
use serde::de::DeserializeOwned;
use serde_json::{json, Value};

/// Deserializa la carga como lo haría Tauri al recibir el `invoke`.
fn payload<T: DeserializeOwned>(value: Value) -> T {
    serde_json::from_value(value).expect("la interfaz manda una carga que el comando no entiende")
}

// ---------------------------------------------------------------------------
// Estructura de tablas
// ---------------------------------------------------------------------------

#[test]
fn crear_una_tabla_traduce_columnas_tipos_y_defaults() {
    let changes: Vec<TableChange> = payload(json!([{
        "kind": "createTable",
        "schema": "public",
        "name": "clientes",
        "columns": [
            { "name": "id", "typeName": "bigint", "notNull": true, "default": null, "identity": "byDefault" },
            { "name": "alta", "typeName": "timestamptz", "notNull": true, "default": "now()", "identity": null }
        ]
    }]));

    let sql = &commands::ddl::ddl_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("CREATE TABLE public.clientes"), "{sql}");
    assert!(sql.contains("id bigint"), "{sql}");
    assert!(sql.contains("NOT NULL"), "{sql}");
    assert!(sql.contains("GENERATED BY DEFAULT AS IDENTITY"), "{sql}");
    // El `default` va crudo a propósito: es una expresión, no un literal a escapar.
    assert!(sql.contains("DEFAULT now()"), "{sql}");
}

#[test]
fn cambiar_el_tipo_de_una_columna_conserva_el_using() {
    let changes: Vec<TableChange> = payload(json!([{
        "kind": "alterColumnType",
        "schema": "public",
        "table": "clientes",
        "column": "edad",
        "typeName": "integer",
        "using": "edad::integer"
    }]));

    let sql = &commands::ddl::ddl_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("TYPE integer"), "{sql}");
    assert!(sql.contains("USING edad::integer"), "{sql}");
}

#[test]
fn un_lote_de_cambios_devuelve_una_sentencia_por_cambio_y_en_orden() {
    let changes: Vec<TableChange> = payload(json!([
        {
            "kind": "addColumn",
            "schema": "public",
            "table": "clientes",
            "column": { "name": "email", "typeName": "text", "notNull": false, "default": null, "identity": null }
        },
        { "kind": "renameColumn", "schema": "public", "table": "clientes", "column": "email", "newName": "correo" },
        { "kind": "dropColumn", "schema": "public", "table": "clientes", "column": "viejo", "cascade": true }
    ]));

    let statements = commands::ddl::ddl_preview(changes).unwrap();
    assert_eq!(statements.len(), 3);
    assert!(
        statements[0].sql.contains("ADD COLUMN email text"),
        "{}",
        statements[0].sql
    );
    assert!(
        statements[1].sql.contains("RENAME COLUMN email TO correo"),
        "{}",
        statements[1].sql
    );
    assert!(
        statements[2].sql.contains("DROP COLUMN viejo CASCADE"),
        "{}",
        statements[2].sql
    );
}

#[test]
fn una_foreign_key_traduce_las_columnas_de_los_dos_lados() {
    let changes: Vec<TableChange> = payload(json!([{
        "kind": "addConstraint",
        "schema": "ventas",
        "table": "pedidos",
        "name": "pedidos_cliente_fkey",
        "definition": {
            "kind": "foreignKey",
            "columns": ["cliente_id"],
            "refSchema": "public",
            "refTable": "clientes",
            "refColumns": ["id"],
            "onDelete": "cascade",
            "onUpdate": null
        }
    }]));

    let sql = &commands::ddl::ddl_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("FOREIGN KEY (cliente_id)"), "{sql}");
    assert!(sql.contains("REFERENCES public.clientes (id)"), "{sql}");
    assert!(sql.contains("ON DELETE CASCADE"), "{sql}");
    assert!(!sql.contains("ON UPDATE"), "{sql}");
}

#[test]
fn los_identificadores_que_lo_necesitan_se_citan_al_cruzar_el_ipc() {
    let changes: Vec<TableChange> = payload(json!([{
        "kind": "dropTable",
        "schema": "public",
        "name": "Mi Tabla",
        "cascade": false
    }]));

    let sql = &commands::ddl::ddl_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("\"Mi Tabla\""), "{sql}");
}

// ---------------------------------------------------------------------------
// Índices, vistas, triggers
// ---------------------------------------------------------------------------

#[test]
fn un_indice_parcial_conserva_unique_metodo_y_predicado() {
    let def: IndexDef = payload(json!({
        "schema": "public",
        "table": "clientes",
        "name": "clientes_correo_activos",
        "unique": true,
        "method": "btree",
        "columns": ["correo"],
        "whereClause": "activo",
        "concurrently": true
    }));

    let sql = commands::ddl::index_preview(def).unwrap().sql;
    assert!(sql.contains("CREATE UNIQUE INDEX CONCURRENTLY"), "{sql}");
    assert!(sql.contains("USING btree"), "{sql}");
    assert!(sql.contains("WHERE activo"), "{sql}");
}

#[test]
fn una_vista_materializada_respeta_el_with_no_data() {
    let changes: Vec<ViewChange> = payload(json!([{
        "kind": "createMaterializedView",
        "schema": "public",
        "name": "ventas_mes",
        "columns": [],
        "query": "SELECT 1",
        "withData": false
    }]));

    let sql = &commands::ddl::view_preview(changes).unwrap()[0].sql;
    assert!(
        sql.contains("CREATE MATERIALIZED VIEW public.ventas_mes"),
        "{sql}"
    );
    assert!(sql.contains("WITH NO DATA"), "{sql}");
}

#[test]
fn un_trigger_traduce_momento_eventos_nivel_y_funcion() {
    let changes: Vec<TriggerChange> = payload(json!([{
        "kind": "createTrigger",
        "schema": "public",
        "table": "clientes",
        "name": "auditar",
        "definition": {
            "timing": "before",
            "events": ["insert", "update"],
            "level": "row",
            "when": "NEW.activo",
            "functionSchema": "audit",
            "functionName": "registrar"
        }
    }]));

    let sql = &commands::ddl::trigger_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("BEFORE INSERT OR UPDATE"), "{sql}");
    assert!(sql.contains("FOR EACH ROW"), "{sql}");
    assert!(sql.contains("WHEN (NEW.activo)"), "{sql}");
    assert!(sql.contains("EXECUTE FUNCTION audit.registrar()"), "{sql}");
}

// ---------------------------------------------------------------------------
// Roles, privilegios y políticas
// ---------------------------------------------------------------------------

#[test]
fn un_rol_nuevo_llega_con_sus_atributos_y_sus_membresias() {
    let changes: Vec<RoleChange> = payload(json!([{
        "kind": "createRole",
        "name": "escritor",
        "attributes": {
            "login": true,
            "connectionLimit": 5,
            "password": "secreta",
            "bypassRls": false
        },
        "memberOf": ["lectores"]
    }]));

    let sql = &commands::ddl::role_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("CREATE ROLE escritor"), "{sql}");
    assert!(sql.contains("LOGIN"), "{sql}");
    assert!(sql.contains("NOBYPASSRLS"), "{sql}");
    assert!(sql.contains("CONNECTION LIMIT 5"), "{sql}");
    // Las membresías del alta van en la misma sentencia, no en un GRANT aparte.
    assert!(sql.contains("IN ROLE lectores"), "{sql}");
}

#[test]
fn la_vista_previa_de_un_rol_muestra_la_sentencia_literal_que_se_va_a_ejecutar() {
    let changes: Vec<RoleChange> = payload(json!([{
        "kind": "createRole",
        "name": "escritor",
        "attributes": { "password": "secreta" },
        "memberOf": []
    }]));

    // Incluida la contraseña: la promesa de la vista previa es que no hay diferencia entre lo que
    // se muestra y lo que corre. Es la contraseña que el usuario acaba de escribir, en su pantalla.
    assert_eq!(
        commands::ddl::role_preview(changes).unwrap()[0].sql,
        "CREATE ROLE escritor WITH PASSWORD 'secreta'"
    );
}

#[test]
fn un_grant_sobre_una_tabla_traduce_los_privilegios_elegidos() {
    let changes: Vec<PrivilegeChange> = payload(json!([{
        "kind": "grant",
        "target": {
            "on": "table",
            "schema": "public",
            "table": "clientes",
            "privileges": ["select", "insert"]
        },
        "grantee": "lectores",
        "grantOption": true
    }]));

    let sql = &commands::ddl::privilege_preview(changes).unwrap()[0].sql;
    assert!(
        sql.contains("GRANT SELECT, INSERT ON public.clientes TO lectores"),
        "{sql}"
    );
    assert!(sql.contains("WITH GRANT OPTION"), "{sql}");
}

#[test]
fn una_politica_manda_solo_la_expresion_que_su_comando_acepta() {
    let changes: Vec<PolicyChange> = payload(json!([{
        "kind": "createPolicy",
        "schema": "public",
        "table": "clientes",
        "name": "solo_propias",
        "definition": {
            "command": "select",
            "kind": "permissive",
            "roles": ["ana"],
            "using": "dueno = current_user",
            "check": null
        }
    }]));

    let sql = &commands::ddl::policy_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("CREATE POLICY solo_propias"), "{sql}");
    assert!(sql.contains("ON public.clientes"), "{sql}");
    assert!(sql.contains("FOR SELECT"), "{sql}");
    assert!(sql.contains("TO ana"), "{sql}");
    assert!(sql.contains("USING (dueno = current_user)"), "{sql}");
    assert!(!sql.contains("WITH CHECK"), "{sql}");
}

#[test]
fn borrar_y_crear_una_politica_sale_en_ese_orden() {
    let changes: Vec<PolicyChange> = payload(json!([
        { "kind": "dropPolicy", "schema": "public", "table": "clientes", "name": "vieja" },
        {
            "kind": "createPolicy",
            "schema": "public",
            "table": "clientes",
            "name": "vieja",
            "definition": {
                "command": "all",
                "kind": "restrictive",
                "roles": [],
                "using": "true",
                "check": null
            }
        }
    ]));

    let statements = commands::ddl::policy_preview(changes).unwrap();
    assert_eq!(statements.len(), 2);
    assert!(
        statements[0].sql.starts_with("DROP POLICY"),
        "{}",
        statements[0].sql
    );
    assert!(
        statements[1].sql.contains("AS RESTRICTIVE"),
        "{}",
        statements[1].sql
    );
    // Sin roles la política alcanza a todo el mundo, y eso se dice explícito.
    assert!(
        statements[1].sql.contains("TO PUBLIC"),
        "{}",
        statements[1].sql
    );
}

#[test]
fn una_extension_se_crea_en_el_esquema_pedido() {
    let changes: Vec<ExtensionChange> = payload(json!([{
        "kind": "create",
        "name": "pg_stat_statements",
        "schema": "public",
        "version": null,
        "cascade": false
    }]));

    let sql = &commands::ddl::extension_preview(changes).unwrap()[0].sql;
    assert!(
        sql.contains("CREATE EXTENSION IF NOT EXISTS pg_stat_statements"),
        "{sql}"
    );
    assert!(sql.contains("SCHEMA public"), "{sql}");
}

// ---------------------------------------------------------------------------
// Configuración del servidor
// ---------------------------------------------------------------------------

#[test]
fn cambiar_y_resetear_un_parametro_no_se_confunden() {
    let changes: Vec<SettingChange> = payload(json!([
        { "kind": "set", "name": "work_mem", "value": "64MB" },
        { "kind": "reset", "name": "log_min_duration_statement" }
    ]));

    let statements = commands::settings::settings_preview(changes);
    assert!(
        statements[0].sql.contains("ALTER SYSTEM SET work_mem"),
        "{}",
        statements[0].sql
    );
    assert!(
        statements[0].sql.contains("'64MB'"),
        "{}",
        statements[0].sql
    );
    assert!(
        statements[1]
            .sql
            .contains("ALTER SYSTEM RESET log_min_duration_statement"),
        "{}",
        statements[1].sql
    );
}

// ---------------------------------------------------------------------------
// Edición de datos
// ---------------------------------------------------------------------------

fn shape() -> TableShape {
    payload(json!({
        "oid": 16384,
        "schema": "public",
        "name": "clientes",
        "columns": [
            { "name": "id", "typeName": "bigint", "notNull": true, "default": null, "generated": true, "comment": null },
            { "name": "correo", "typeName": "text", "notNull": false, "default": null, "generated": false, "comment": null }
        ],
        "key": { "name": "clientes_pkey", "kind": "primary", "columns": ["id"] },
        "readOnly": null
    }))
}

#[test]
fn un_update_lleva_los_valores_originales_para_detectar_el_conflicto() {
    let changes: Vec<Change> = payload(json!([{
        "kind": "update",
        "key": ["7"],
        "original": { "correo": "viejo@ejemplo" },
        "changes": { "correo": "nuevo@ejemplo" }
    }]));

    let statement = &commands::data::data_preview(shape(), changes).unwrap()[0];
    assert!(
        statement.sql.starts_with("UPDATE public.clientes"),
        "{}",
        statement.sql
    );
    // El valor viejo viaja como parámetro: es lo que hace que un cambio ajeno se reporte como
    // conflicto en vez de pisarse.
    assert!(statement
        .params
        .iter()
        .any(|p| p.as_deref() == Some("viejo@ejemplo")));
    assert!(statement
        .params
        .iter()
        .any(|p| p.as_deref() == Some("nuevo@ejemplo")));
}

#[test]
fn los_valores_de_las_celdas_cruzan_como_texto_y_el_null_se_distingue_del_vacio() {
    let changes: Vec<Change> = payload(json!([{
        "kind": "insert",
        "values": { "correo": null }
    }]));

    let statement = &commands::data::data_preview(shape(), changes).unwrap()[0];
    assert!(
        statement.sql.starts_with("INSERT INTO public.clientes"),
        "{}",
        statement.sql
    );
    assert_eq!(statement.params, vec![None]);
}

// ---------------------------------------------------------------------------
// Import/export con COPY
// ---------------------------------------------------------------------------

#[test]
fn exportar_una_consulta_arma_el_copy_con_las_opciones_de_csv() {
    let spec: ExportSpec = payload(json!({
        "source": { "kind": "query", "sql": "SELECT 1" },
        "format": "csv",
        "options": { "header": true, "delimiter": ";", "quote": "'", "null": "\\N" }
    }));

    let sql = commands::data::data_export_preview(spec).unwrap().sql;
    assert!(sql.contains("COPY (SELECT 1) TO STDOUT"), "{sql}");
    assert!(sql.contains("FORMAT csv"), "{sql}");
    assert!(sql.contains("HEADER"), "{sql}");
    assert!(sql.contains("DELIMITER ';'"), "{sql}");
}

#[test]
fn importar_a_columnas_elegidas_las_lista_en_el_copy() {
    let spec: ImportSpec = payload(json!({
        "schema": "public",
        "table": "clientes",
        "columns": ["id", "correo"],
        "format": "csv",
        "options": { "header": true }
    }));

    let sql = commands::data::data_import_preview(spec).unwrap().sql;
    assert!(
        sql.contains("COPY public.clientes (id, correo) FROM STDIN"),
        "{sql}"
    );
    assert!(sql.contains("HEADER"), "{sql}");
}

// ---------------------------------------------------------------------------
// Editor de consultas
// ---------------------------------------------------------------------------

#[test]
fn la_sentencia_bajo_el_cursor_es_la_que_se_va_a_ejecutar() {
    let sql = "SELECT 1;\nSELECT 2;";
    let segunda = commands::query::statement_at_cursor(sql.to_owned(), 12).unwrap();
    assert_eq!(segunda.text.trim(), "SELECT 2");

    let primera = commands::query::statement_at_cursor(sql.to_owned(), 0).unwrap();
    assert_eq!(primera.text.trim(), "SELECT 1");
}

#[test]
fn explain_analyze_avisa_antes_de_ejecutar_algo_que_modifica() {
    let options = payload(json!({ "analyze": true, "buffers": false, "verbose": false }));
    let aviso = commands::query::explain_warning("DELETE FROM clientes".to_owned(), Some(options));
    assert!(aviso.is_some());

    let options = payload(json!({ "analyze": false, "buffers": false, "verbose": false }));
    // Sin ANALYZE el plan no ejecuta nada: no hay nada de qué avisar.
    assert!(
        commands::query::explain_warning("DELETE FROM clientes".to_owned(), Some(options))
            .is_none()
    );
}

// ---------------------------------------------------------------------------
// Secuencias, tipos, dominios, esquemas y bases
// ---------------------------------------------------------------------------

#[test]
fn crear_una_secuencia_traduce_sus_opciones() {
    let changes: Vec<SequenceChange> = payload(json!([{
        "kind": "createSequence",
        "schema": "public",
        "name": "folios",
        "ifNotExists": true,
        "options": {
            "dataType": "integer",
            "increment": 5,
            "minValue": 100,
            "maxValue": 1000,
            "start": 100,
            "cache": 1,
            "cycle": true,
            "ownedBy": {
                "kind": "column",
                "schema": "public",
                "table": "comprobantes",
                "column": "folio"
            }
        }
    }]));

    let sql = &commands::ddl::sequence_preview(changes).unwrap()[0].sql;
    assert!(
        sql.contains("CREATE SEQUENCE IF NOT EXISTS public.folios"),
        "{sql}"
    );
    assert!(sql.contains("AS integer"), "{sql}");
    assert!(sql.contains("INCREMENT BY 5"), "{sql}");
    assert!(sql.contains("MINVALUE 100 MAXVALUE 1000"), "{sql}");
    assert!(sql.contains("OWNED BY public.comprobantes.folio"), "{sql}");
}

#[test]
fn reiniciar_una_secuencia_no_toca_su_start() {
    let changes: Vec<SequenceChange> = payload(json!([{
        "kind": "restartSequence",
        "schema": "public",
        "name": "folios",
        "value": 1
    }]));

    let sql = &commands::ddl::sequence_preview(changes).unwrap()[0].sql;
    assert_eq!(sql, "ALTER SEQUENCE public.folios RESTART WITH 1");
}

#[test]
fn agregar_un_valor_a_una_enumeracion_respeta_la_posicion() {
    let changes: Vec<TypeChange> = payload(json!([{
        "kind": "addEnumValue",
        "schema": "public",
        "name": "estado",
        "value": "pausado",
        "position": { "kind": "before", "value": "inactivo" },
        "ifNotExists": true
    }]));

    let sql = &commands::ddl::type_preview(changes).unwrap()[0].sql;
    assert_eq!(
        sql,
        "ALTER TYPE public.estado ADD VALUE IF NOT EXISTS 'pausado' BEFORE 'inactivo'"
    );
}

#[test]
fn crear_un_compuesto_traduce_sus_campos() {
    let changes: Vec<TypeChange> = payload(json!([{
        "kind": "createComposite",
        "schema": "public",
        "name": "direccion",
        "fields": [
            { "name": "calle", "dataType": "text", "collation": null },
            { "name": "numero", "dataType": "integer", "collation": null }
        ]
    }]));

    let sql = &commands::ddl::type_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("calle text"), "{sql}");
    assert!(sql.contains("numero integer"), "{sql}");
}

#[test]
fn crear_un_dominio_conserva_el_check_crudo() {
    let changes: Vec<DomainChange> = payload(json!([{
        "kind": "createDomain",
        "schema": "public",
        "name": "correo",
        "dataType": "text",
        "collation": null,
        "default": null,
        "notNull": true,
        "constraints": [
            { "name": "correo_valido", "check": "VALUE ~ '@'", "notValid": false }
        ]
    }]));

    let sql = &commands::ddl::domain_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("CREATE DOMAIN public.correo AS text"), "{sql}");
    assert!(sql.contains("NOT NULL"), "{sql}");
    // La expresión va cruda: es lo que escribió el usuario, no un literal a escapar.
    assert!(
        sql.contains("CONSTRAINT correo_valido CHECK (VALUE ~ '@')"),
        "{sql}"
    );
}

#[test]
fn crear_un_esquema_traduce_su_autorizacion() {
    let changes: Vec<SchemaChange> = payload(json!([{
        "kind": "createSchema",
        "name": "ventas",
        "authorization": "analistas",
        "ifNotExists": true
    }]));

    let sql = &commands::ddl::schema_preview(changes).unwrap()[0].sql;
    assert_eq!(
        sql,
        "CREATE SCHEMA IF NOT EXISTS ventas AUTHORIZATION analistas"
    );
}

#[test]
fn crear_una_base_traduce_sus_opciones() {
    let changes: Vec<DatabaseChange> = payload(json!([{
        "kind": "createDatabase",
        "name": "ventas",
        "options": {
            "owner": "analistas",
            "template": "template0",
            "encoding": "UTF8",
            "lcCollate": "es_AR.UTF-8",
            "lcCtype": "es_AR.UTF-8",
            "connectionLimit": 10,
            "isTemplate": false
        }
    }]));

    let sql = &commands::ddl::database_preview(changes).unwrap()[0].sql;
    assert!(sql.contains("OWNER = analistas"), "{sql}");
    assert!(sql.contains("TEMPLATE = template0"), "{sql}");
    // El encoding y los locales son literales, no identificadores.
    assert!(sql.contains("ENCODING = 'UTF8'"), "{sql}");
    assert!(sql.contains("LC_COLLATE = 'es_AR.UTF-8'"), "{sql}");
    assert!(sql.contains("CONNECTION LIMIT = 10"), "{sql}");
}

#[test]
fn borrar_una_base_con_force_echa_a_las_sesiones() {
    let changes: Vec<DatabaseChange> = payload(json!([{
        "kind": "dropDatabase",
        "name": "ventas",
        "ifExists": true,
        "force": true
    }]));

    let sql = &commands::ddl::database_preview(changes).unwrap()[0].sql;
    assert_eq!(sql, "DROP DATABASE IF EXISTS ventas WITH (FORCE)");
}

#[test]
fn comentar_una_columna_la_nombra_con_su_tabla() {
    let changes: Vec<CommentChange> = payload(json!([{
        "target": {
            "kind": "column",
            "schema": "public",
            "table": "clientes",
            "column": "estado"
        },
        "comment": "activo | inactivo"
    }]));

    let sql = &commands::ddl::comment_preview(changes).unwrap()[0].sql;
    assert_eq!(
        sql,
        "COMMENT ON COLUMN public.clientes.estado IS 'activo | inactivo'"
    );
}

#[test]
fn un_comentario_sin_texto_lo_borra() {
    let changes: Vec<CommentChange> = payload(json!([{
        "target": { "kind": "schema", "name": "ventas" },
        "comment": null
    }]));

    let sql = &commands::ddl::comment_preview(changes).unwrap()[0].sql;
    assert_eq!(sql, "COMMENT ON SCHEMA ventas IS NULL");
}

// ---------------------------------------------------------------------------
// Diagrama ERD
// ---------------------------------------------------------------------------

#[test]
fn exportar_el_diagrama_escribe_el_svg_tal_cual_lo_dibujo_la_interfaz() {
    let path = std::env::temp_dir().join(format!("pgforge_erd_{}.svg", std::process::id()));
    let svg = "<svg xmlns=\"http://www.w3.org/2000/svg\"><rect/></svg>";

    commands::schema::erd_export_svg(path.to_string_lossy().into_owned(), svg.to_owned()).unwrap();
    let escrito = std::fs::read_to_string(&path).unwrap();
    let _ = std::fs::remove_file(&path);

    // El archivo es exactamente lo que se vio en pantalla, no una reconstrucción parecida.
    assert_eq!(escrito, svg);
}
