//! Crear, cambiar y borrar tablas y sus columnas.
//!
//! Es el reverso de lo que hace el resto de [`crate::ddl`]: allá se lee lo que ya existe para
//! mostrarlo, acá se arma el DDL que hace falta ejecutar para que exista, cambie o desaparezca.
//!
//! El `DEFAULT` de una columna y el `USING` de un cambio de tipo son SQL crudo, no un literal que
//! haya que escapar: no hay forma de parametrizar ninguno de los dos en una sentencia DDL, así que
//! el texto se manda tal cual el usuario lo escribió. Es la misma frontera de confianza que ya
//! tiene el editor de consultas: lo ejecuta el propio usuario autenticado, con sus propios
//! privilegios.
//!
//! El tipo de una columna tampoco se cita: como en [`crate::data::shape::Column`], es el servidor
//! el que valida si es un tipo que existe al ejecutar la sentencia.

use serde::{Deserialize, Serialize};

use crate::conn::ServerHandle;
use crate::error::{Error, Result};

use super::{qualified, quote_ident};

/// Cómo genera sus valores una columna de identidad.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum Identity {
    /// `GENERATED ALWAYS AS IDENTITY`: un `INSERT` que manda un valor propio falla.
    Always,
    /// `GENERATED BY DEFAULT AS IDENTITY`: un `INSERT` puede pisar el valor generado.
    ByDefault,
}

/// Una columna nueva, para `CREATE TABLE` o `ADD COLUMN`.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnDef {
    pub name: String,
    pub type_name: String,
    pub not_null: bool,
    pub default: Option<String>,
    pub identity: Option<Identity>,
}

/// Qué hacer con las filas del otro lado cuando la referenciada cambia o desaparece.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RefAction {
    Cascade,
    SetNull,
    SetDefault,
    Restrict,
    NoAction,
}

impl RefAction {
    fn sql(self) -> &'static str {
        match self {
            RefAction::Cascade => "CASCADE",
            RefAction::SetNull => "SET NULL",
            RefAction::SetDefault => "SET DEFAULT",
            RefAction::Restrict => "RESTRICT",
            RefAction::NoAction => "NO ACTION",
        }
    }
}

/// Postgres no tiene un "ALTER CONSTRAINT" que cambie su definición: se borra y se crea de nuevo,
/// así que acá no hace falta nada parecido a `AlterColumnType`.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum ConstraintDef {
    PrimaryKey {
        columns: Vec<String>,
    },
    Unique {
        columns: Vec<String>,
    },
    ForeignKey {
        columns: Vec<String>,
        ref_schema: String,
        ref_table: String,
        ref_columns: Vec<String>,
        on_delete: Option<RefAction>,
        on_update: Option<RefAction>,
    },
    /// SQL crudo, misma frontera de confianza que el `default` de una columna.
    Check {
        expression: String,
    },
}

/// Un cambio de estructura pendiente.
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum TableChange {
    CreateTable {
        schema: String,
        name: String,
        columns: Vec<ColumnDef>,
    },
    DropTable {
        schema: String,
        name: String,
        cascade: bool,
    },
    RenameTable {
        schema: String,
        name: String,
        new_name: String,
    },
    AddColumn {
        schema: String,
        table: String,
        column: ColumnDef,
    },
    DropColumn {
        schema: String,
        table: String,
        column: String,
        cascade: bool,
    },
    RenameColumn {
        schema: String,
        table: String,
        column: String,
        new_name: String,
    },
    AlterColumnType {
        schema: String,
        table: String,
        column: String,
        type_name: String,
        using: Option<String>,
    },
    SetColumnNotNull {
        schema: String,
        table: String,
        column: String,
        not_null: bool,
    },
    SetColumnDefault {
        schema: String,
        table: String,
        column: String,
        default: Option<String>,
    },
    AddConstraint {
        schema: String,
        table: String,
        name: String,
        definition: ConstraintDef,
    },
    DropConstraint {
        schema: String,
        table: String,
        name: String,
        cascade: bool,
    },
}

/// Una sentencia lista para ejecutar. El DDL no admite parámetros: a diferencia de
/// [`crate::data::edit::Statement`], el texto ya está completo.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Statement {
    pub sql: String,
}

fn statement(sql: String) -> Statement {
    Statement { sql }
}

/// Traduce los cambios pendientes a SQL.
pub fn statements(changes: &[TableChange]) -> Result<Vec<Statement>> {
    changes.iter().map(one).collect()
}

fn one(change: &TableChange) -> Result<Statement> {
    match change {
        TableChange::CreateTable {
            schema,
            name,
            columns,
        } => create_table(schema, name, columns),
        TableChange::DropTable {
            schema,
            name,
            cascade,
        } => Ok(statement(format!(
            "DROP TABLE {}{}",
            qualified(schema, name),
            if *cascade { " CASCADE" } else { "" }
        ))),
        TableChange::RenameTable {
            schema,
            name,
            new_name,
        } => Ok(statement(format!(
            "ALTER TABLE {} RENAME TO {}",
            qualified(schema, name),
            quote_ident(new_name)
        ))),
        TableChange::AddColumn {
            schema,
            table,
            column,
        } => Ok(statement(format!(
            "ALTER TABLE {} ADD COLUMN {}",
            qualified(schema, table),
            column_sql(column)?
        ))),
        TableChange::DropColumn {
            schema,
            table,
            column,
            cascade,
        } => Ok(statement(format!(
            "ALTER TABLE {} DROP COLUMN {}{}",
            qualified(schema, table),
            quote_ident(column),
            if *cascade { " CASCADE" } else { "" }
        ))),
        TableChange::RenameColumn {
            schema,
            table,
            column,
            new_name,
        } => Ok(statement(format!(
            "ALTER TABLE {} RENAME COLUMN {} TO {}",
            qualified(schema, table),
            quote_ident(column),
            quote_ident(new_name)
        ))),
        TableChange::AlterColumnType {
            schema,
            table,
            column,
            type_name,
            using,
        } => {
            let mut sql = format!(
                "ALTER TABLE {} ALTER COLUMN {} TYPE {type_name}",
                qualified(schema, table),
                quote_ident(column)
            );
            if let Some(using) = using {
                sql.push_str(&format!(" USING {using}"));
            }
            Ok(statement(sql))
        }
        TableChange::SetColumnNotNull {
            schema,
            table,
            column,
            not_null,
        } => Ok(statement(format!(
            "ALTER TABLE {} ALTER COLUMN {} {}",
            qualified(schema, table),
            quote_ident(column),
            if *not_null { "SET NOT NULL" } else { "DROP NOT NULL" }
        ))),
        TableChange::SetColumnDefault {
            schema,
            table,
            column,
            default,
        } => Ok(statement(format!(
            "ALTER TABLE {} ALTER COLUMN {} {}",
            qualified(schema, table),
            quote_ident(column),
            match default {
                Some(default) => format!("SET DEFAULT {default}"),
                None => "DROP DEFAULT".to_owned(),
            }
        ))),
        TableChange::AddConstraint {
            schema,
            table,
            name,
            definition,
        } => Ok(statement(format!(
            "ALTER TABLE {} ADD CONSTRAINT {} {}",
            qualified(schema, table),
            quote_ident(name),
            constraint_sql(definition)?
        ))),
        TableChange::DropConstraint {
            schema,
            table,
            name,
            cascade,
        } => Ok(statement(format!(
            "ALTER TABLE {} DROP CONSTRAINT {}{}",
            qualified(schema, table),
            quote_ident(name),
            if *cascade { " CASCADE" } else { "" }
        ))),
    }
}

fn constraint_sql(definition: &ConstraintDef) -> Result<String> {
    match definition {
        ConstraintDef::PrimaryKey { columns } => {
            Ok(format!("PRIMARY KEY ({})", column_list(columns)?))
        }
        ConstraintDef::Unique { columns } => Ok(format!("UNIQUE ({})", column_list(columns)?)),
        ConstraintDef::ForeignKey {
            columns,
            ref_schema,
            ref_table,
            ref_columns,
            on_delete,
            on_update,
        } => {
            let mut sql = format!(
                "FOREIGN KEY ({}) REFERENCES {} ({})",
                column_list(columns)?,
                qualified(ref_schema, ref_table),
                column_list(ref_columns)?
            );
            if let Some(action) = on_delete {
                sql.push_str(&format!(" ON DELETE {}", action.sql()));
            }
            if let Some(action) = on_update {
                sql.push_str(&format!(" ON UPDATE {}", action.sql()));
            }
            Ok(sql)
        }
        ConstraintDef::Check { expression } => {
            if expression.trim().is_empty() {
                return Err(Error::Config(
                    "un CHECK necesita una expresión".to_owned(),
                ));
            }
            Ok(format!("CHECK ({expression})"))
        }
    }
}

fn column_list(columns: &[String]) -> Result<String> {
    if columns.is_empty() {
        return Err(Error::Config(
            "una constraint necesita al menos una columna".to_owned(),
        ));
    }
    Ok(columns.iter().map(|c| quote_ident(c)).collect::<Vec<_>>().join(", "))
}

fn create_table(schema: &str, name: &str, columns: &[ColumnDef]) -> Result<Statement> {
    if columns.is_empty() {
        return Err(Error::Config(
            "una tabla necesita al menos una columna".to_owned(),
        ));
    }

    let defined: Vec<String> = columns
        .iter()
        .map(column_sql)
        .collect::<Result<_>>()?;

    Ok(statement(format!(
        "CREATE TABLE {} (\n    {}\n)",
        qualified(schema, name),
        defined.join(",\n    ")
    )))
}

fn column_sql(column: &ColumnDef) -> Result<String> {
    if column.name.is_empty() {
        return Err(Error::Config(
            "una columna necesita un nombre".to_owned(),
        ));
    }
    if column.type_name.is_empty() {
        return Err(Error::Config(format!(
            "la columna {} necesita un tipo",
            column.name
        )));
    }

    let mut sql = format!("{} {}", quote_ident(&column.name), column.type_name);

    match column.identity {
        // Una columna de identidad calcula su propio valor: no tiene sentido combinarla con un
        // DEFAULT propio, y PostgreSQL lo rechaza.
        Some(Identity::Always) => sql.push_str(" GENERATED ALWAYS AS IDENTITY"),
        Some(Identity::ByDefault) => sql.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
        None => {
            if let Some(default) = &column.default {
                sql.push_str(&format!(" DEFAULT {default}"));
            }
        }
    }

    if column.not_null {
        sql.push_str(" NOT NULL");
    }

    Ok(sql)
}

/// Aplica los cambios en una sola transacción: la tabla queda entera o como estaba.
pub async fn apply(handle: &ServerHandle, database: &str, changes: &[TableChange]) -> Result<()> {
    let statements = statements(changes)?;
    let mut client = handle.client(database).await?;
    let transaction = client.transaction().await?;

    for statement in &statements {
        transaction.batch_execute(&statement.sql).await?;
    }

    transaction.commit().await?;
    Ok(())
}

/// Una constraint tal como ya existe, para mostrarla y ofrecer borrarla. No hay nada que editar en
/// el lugar: cambiarla es borrarla y agregar una nueva (ver el comentario en [`ConstraintDef`]).
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ConstraintInfo {
    pub oid: u32,
    pub name: String,
    /// Etiqueta para mostrar ("primaria", "foránea", ...), no un valor para volver a interpretar.
    pub kind: String,
    pub definition: String,
}

const CONSTRAINTS_SQL: &str = "
    SELECT con.oid,
           con.conname::text,
           con.contype::text,
           pg_catalog.pg_get_constraintdef(con.oid, true)
      FROM pg_catalog.pg_constraint con
     WHERE con.conrelid = $1
     ORDER BY con.conname
";

/// Las constraints que ya tiene una tabla. Misma consulta que usa el árbol para mostrarlas
/// (`introspect::constraints`), pero en una estructura en vez de un `TreeNode` con el texto ya
/// armado: acá hace falta el nombre y el oid por separado para poder borrarlas desde la interfaz.
pub async fn constraints(
    handle: &ServerHandle,
    database: &str,
    oid: u32,
) -> Result<Vec<ConstraintInfo>> {
    let client = handle.client(database).await?;
    let rows = client.query(CONSTRAINTS_SQL, &[&oid]).await?;

    Ok(rows
        .into_iter()
        .map(|row| {
            let contype: String = row.get(2);
            ConstraintInfo {
                oid: row.get(0),
                name: row.get(1),
                kind: constraint_kind_label(&contype).to_owned(),
                definition: row.get(3),
            }
        })
        .collect())
}

fn constraint_kind_label(contype: &str) -> &'static str {
    match contype {
        "p" => "primaria",
        "f" => "foránea",
        "u" => "única",
        "c" => "verificación",
        "x" => "exclusión",
        _ => "restricción",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn column(name: &str, type_name: &str) -> ColumnDef {
        ColumnDef {
            name: name.into(),
            type_name: type_name.into(),
            not_null: false,
            default: None,
            identity: None,
        }
    }

    fn one_statement(change: TableChange) -> Statement {
        statements(&[change])
            .expect("tenía que generar la sentencia")
            .remove(0)
    }

    #[test]
    fn crea_una_tabla_con_sus_columnas() {
        let statement = one_statement(TableChange::CreateTable {
            schema: "public".into(),
            name: "clientes".into(),
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    type_name: "bigint".into(),
                    not_null: false,
                    default: None,
                    identity: Some(Identity::Always),
                },
                {
                    let mut nombre = column("nombre", "text");
                    nombre.not_null = true;
                    nombre
                },
                {
                    let mut total = column("total", "numeric(12,2)");
                    total.default = Some("0".into());
                    total
                },
            ],
        });

        assert_eq!(
            statement.sql,
            "CREATE TABLE public.clientes (\n    \
             id bigint GENERATED ALWAYS AS IDENTITY,\n    \
             nombre text NOT NULL,\n    \
             total numeric(12,2) DEFAULT 0\n)"
        );
    }

    #[test]
    fn una_tabla_sin_columnas_no_se_genera() {
        assert!(statements(&[TableChange::CreateTable {
            schema: "public".into(),
            name: "vacia".into(),
            columns: vec![],
        }])
        .is_err());
    }

    #[test]
    fn una_columna_de_identidad_no_lleva_default_propio() {
        let statement = one_statement(TableChange::CreateTable {
            schema: "public".into(),
            name: "t".into(),
            columns: vec![ColumnDef {
                name: "id".into(),
                type_name: "bigint".into(),
                not_null: false,
                default: Some("42".into()),
                identity: Some(Identity::ByDefault),
            }],
        });

        assert!(
            statement.sql.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "{}",
            statement.sql
        );
        assert!(!statement.sql.contains("DEFAULT 42"), "{}", statement.sql);
    }

    #[test]
    fn el_drop_table_lleva_cascade_si_se_pide() {
        let statement = one_statement(TableChange::DropTable {
            schema: "public".into(),
            name: "clientes".into(),
            cascade: true,
        });
        assert_eq!(statement.sql, "DROP TABLE public.clientes CASCADE");

        let statement = one_statement(TableChange::DropTable {
            schema: "public".into(),
            name: "clientes".into(),
            cascade: false,
        });
        assert_eq!(statement.sql, "DROP TABLE public.clientes");
    }

    #[test]
    fn agrega_una_columna() {
        let statement = one_statement(TableChange::AddColumn {
            schema: "public".into(),
            table: "clientes".into(),
            column: {
                let mut activo = column("activo", "boolean");
                activo.not_null = true;
                activo.default = Some("true".into());
                activo
            },
        });

        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ADD COLUMN activo boolean DEFAULT true NOT NULL"
        );
    }

    #[test]
    fn borra_una_columna() {
        let statement = one_statement(TableChange::DropColumn {
            schema: "public".into(),
            table: "clientes".into(),
            column: "activo".into(),
            cascade: false,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes DROP COLUMN activo"
        );
    }

    #[test]
    fn cambia_el_tipo_de_una_columna_con_using() {
        let statement = one_statement(TableChange::AlterColumnType {
            schema: "public".into(),
            table: "clientes".into(),
            column: "codigo".into(),
            type_name: "integer".into(),
            using: Some("codigo::integer".into()),
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN codigo TYPE integer \
             USING codigo::integer"
        );
    }

    #[test]
    fn cambia_el_tipo_de_una_columna_sin_using() {
        let statement = one_statement(TableChange::AlterColumnType {
            schema: "public".into(),
            table: "clientes".into(),
            column: "nota".into(),
            type_name: "varchar(200)".into(),
            using: None,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN nota TYPE varchar(200)"
        );
    }

    #[test]
    fn pone_y_quita_not_null() {
        let statement = one_statement(TableChange::SetColumnNotNull {
            schema: "public".into(),
            table: "clientes".into(),
            column: "nombre".into(),
            not_null: true,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN nombre SET NOT NULL"
        );

        let statement = one_statement(TableChange::SetColumnNotNull {
            schema: "public".into(),
            table: "clientes".into(),
            column: "nombre".into(),
            not_null: false,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN nombre DROP NOT NULL"
        );
    }

    #[test]
    fn pone_y_quita_el_default() {
        let statement = one_statement(TableChange::SetColumnDefault {
            schema: "public".into(),
            table: "clientes".into(),
            column: "estado".into(),
            default: Some("'nuevo'".into()),
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN estado SET DEFAULT 'nuevo'"
        );

        let statement = one_statement(TableChange::SetColumnDefault {
            schema: "public".into(),
            table: "clientes".into(),
            column: "estado".into(),
            default: None,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ALTER COLUMN estado DROP DEFAULT"
        );
    }

    #[test]
    fn renombra_tabla_y_columna() {
        let statement = one_statement(TableChange::RenameTable {
            schema: "public".into(),
            name: "clientes".into(),
            new_name: "customers".into(),
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes RENAME TO customers"
        );

        let statement = one_statement(TableChange::RenameColumn {
            schema: "public".into(),
            table: "clientes".into(),
            column: "nombre".into(),
            new_name: "name".into(),
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes RENAME COLUMN nombre TO name"
        );
    }

    #[test]
    fn cita_los_identificadores_que_lo_necesitan() {
        let statement = one_statement(TableChange::CreateTable {
            schema: "mi esquema".into(),
            name: "Clientes".into(),
            columns: vec![column("id de cliente", "bigint")],
        });
        assert!(
            statement.sql.contains("\"mi esquema\".\"Clientes\""),
            "{}",
            statement.sql
        );
        assert!(
            statement.sql.contains("\"id de cliente\" bigint"),
            "{}",
            statement.sql
        );
    }

    #[test]
    fn una_columna_sin_nombre_no_se_genera() {
        assert!(statements(&[TableChange::AddColumn {
            schema: "public".into(),
            table: "clientes".into(),
            column: column("", "text"),
        }])
        .is_err());
    }

    #[test]
    fn una_columna_sin_tipo_no_se_genera() {
        assert!(statements(&[TableChange::AddColumn {
            schema: "public".into(),
            table: "clientes".into(),
            column: column("nombre", ""),
        }])
        .is_err());
    }

    #[test]
    fn agrega_una_primary_key() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "clientes_pkey".into(),
            definition: ConstraintDef::PrimaryKey {
                columns: vec!["id".into()],
            },
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ADD CONSTRAINT clientes_pkey PRIMARY KEY (id)"
        );
    }

    #[test]
    fn agrega_un_unique_con_clave_compuesta() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "clientes_codigo_key".into(),
            definition: ConstraintDef::Unique {
                columns: vec!["codigo".into(), "sucursal".into()],
            },
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ADD CONSTRAINT clientes_codigo_key \
             UNIQUE (codigo, sucursal)"
        );
    }

    #[test]
    fn agrega_una_foreign_key_con_acciones() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "ventas".into(),
            name: "ventas_cliente_fkey".into(),
            definition: ConstraintDef::ForeignKey {
                columns: vec!["cliente_id".into()],
                ref_schema: "public".into(),
                ref_table: "clientes".into(),
                ref_columns: vec!["id".into()],
                on_delete: Some(RefAction::Cascade),
                on_update: Some(RefAction::NoAction),
            },
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.ventas ADD CONSTRAINT ventas_cliente_fkey \
             FOREIGN KEY (cliente_id) REFERENCES public.clientes (id) \
             ON DELETE CASCADE ON UPDATE NO ACTION"
        );
    }

    #[test]
    fn una_foreign_key_sin_acciones_no_las_menciona() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "ventas".into(),
            name: "ventas_cliente_fkey".into(),
            definition: ConstraintDef::ForeignKey {
                columns: vec!["cliente_id".into()],
                ref_schema: "public".into(),
                ref_table: "clientes".into(),
                ref_columns: vec!["id".into()],
                on_delete: None,
                on_update: None,
            },
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.ventas ADD CONSTRAINT ventas_cliente_fkey \
             FOREIGN KEY (cliente_id) REFERENCES public.clientes (id)"
        );
    }

    #[test]
    fn agrega_un_check() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "clientes_total_check".into(),
            definition: ConstraintDef::Check {
                expression: "total >= 0".into(),
            },
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes ADD CONSTRAINT clientes_total_check \
             CHECK (total >= 0)"
        );
    }

    #[test]
    fn un_check_sin_expresion_no_se_genera() {
        assert!(statements(&[TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "x".into(),
            definition: ConstraintDef::Check {
                expression: "  ".into(),
            },
        }])
        .is_err());
    }

    #[test]
    fn una_constraint_sin_columnas_no_se_genera() {
        assert!(statements(&[TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "x".into(),
            definition: ConstraintDef::Unique { columns: vec![] },
        }])
        .is_err());
    }

    #[test]
    fn borra_una_constraint_con_y_sin_cascade() {
        let statement = one_statement(TableChange::DropConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "clientes_pkey".into(),
            cascade: false,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes DROP CONSTRAINT clientes_pkey"
        );

        let statement = one_statement(TableChange::DropConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "clientes_pkey".into(),
            cascade: true,
        });
        assert_eq!(
            statement.sql,
            "ALTER TABLE public.clientes DROP CONSTRAINT clientes_pkey CASCADE"
        );
    }

    #[test]
    fn cita_los_nombres_de_columna_de_una_constraint() {
        let statement = one_statement(TableChange::AddConstraint {
            schema: "public".into(),
            table: "clientes".into(),
            name: "pk".into(),
            definition: ConstraintDef::PrimaryKey {
                columns: vec!["id de cliente".into()],
            },
        });
        assert!(
            statement.sql.contains("PRIMARY KEY (\"id de cliente\")"),
            "{}",
            statement.sql
        );
    }
}
